### ISSUE TITLE
Won't Load UI

### ISSUE THREAD

**Issue by grempe** [githubocto/flat-editor#9]
I've just installed Flat Editor, but I can't get past the initialization step. It always hangs, and displays no UI.  I only see a new tab for 'flat.yml (Working Tree)' and a blue loading bar that slides from left to right forever.

Trying to debug I tried installing an older version of the extension, I tried disabling ALL extensions but this one, and nothing worked. Same result. VS Code console shows a number of entities being downloaded, all with HTTP 200 responses.

I've also deleted the `.github` folder a number of times to reset with no change on init.

The `flat.yml` file does have some contents.

```
❯ cat flat.yml 
name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
```

Stuck.

![Screen Recording 2021-05-19 at 01 02 24](https://user-images.githubusercontent.com/117/118758963-036eac80-b83e-11eb-9be4-ea4d9009a8e8.gif)
